version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: supermare_mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - supermare-data:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: supermare_phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
          - "${PHPMYADMIN_PORT}:80"
      links:
          - mysql
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/supermare:/usr/src/app'
      - 'www:/usr/src/app'
    container_name: supermare_php
    restart: on-failure
    env_file:
      - .env
  nginx:
    image: nginx:1.15-alpine
    container_name: supermare_nginx
    restart: on-failure
    volumes:
      - 'www:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
volumes:
  www:
  supermare-data: