version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: prototype_mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - prototype-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './app:/var/www'
    container_name: prototype_php
    restart: on-failure
    env_file:
      - .env
  nginx:
    image: nginx:1.15-alpine
    container_name: prototype_nginx
    restart: on-failure
    volumes:
      - './app:/var/www'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
volumes:
  www:
  prototype-data: